# Generated by Django 5.0.4 on 2024-05-15 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="age",
            field=models.BigIntegerField(default=13),
        ),
    ]
