# Generated by Django 5.0.4 on 2024-05-15 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_user_age"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="pimage",
            field=models.ImageField(default="", upload_to="pimage/"),
        ),
    ]
