# Generated by Django 5.0.4 on 2024-05-18 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0003_user_pimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="pimage",
            field=models.ImageField(default=" ", upload_to="pimage/"),
        ),
    ]
