# Generated by Django 5.0.4 on 2024-06-12 10:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0004_alter_user_pimage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="pimage",
            new_name="profile",
        ),
    ]
