# Generated by Django 5.0.4 on 2024-06-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0005_rename_pimage_user_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="usertype",
            field=models.CharField(default="", max_length=20),
        ),
    ]
