# Generated by Django 5.0.4 on 2024-06-13 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0006_user_usertype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="usertype",
            field=models.CharField(default="buyer", max_length=20),
        ),
    ]
