# Generated by Django 5.0.4 on 2024-06-17 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0007_alter_user_usertype"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pcategory",
                    models.CharField(
                        choices=[("Juice", "Juice"), ("Fruits", "Fruits")],
                        max_length=20,
                    ),
                ),
                ("pprice", models.PositiveIntegerField()),
                ("pname", models.CharField(max_length=50)),
                ("pdec", models.TextField()),
                ("pimage", models.ImageField(default="", upload_to="product/")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.user"
                    ),
                ),
            ],
        ),
    ]
