# Generated by Django 5.0.4 on 2024-06-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0009_alter_user_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile",
            field=models.ImageField(default="", upload_to="pictures/"),
        ),
    ]
