# Generated by Django 5.0.6 on 2024-06-20 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0010_alter_user_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Wishlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wprice", models.PositiveIntegerField()),
                ("wname", models.CharField(max_length=50)),
                ("wdec", models.TextField()),
                ("wimage", models.ImageField(default="", upload_to="wproduct/")),
                (
                    "wish",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.product"
                    ),
                ),
            ],
        ),
    ]
