# Generated by Django 5.0.6 on 2024-06-22 13:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0011_wishlist"),
    ]

    operations = [
        migrations.RenameField(
            model_name="wishlist",
            old_name="wish",
            new_name="product",
        ),
        migrations.RemoveField(
            model_name="wishlist",
            name="wdec",
        ),
        migrations.RemoveField(
            model_name="wishlist",
            name="wimage",
        ),
        migrations.RemoveField(
            model_name="wishlist",
            name="wname",
        ),
        migrations.RemoveField(
            model_name="wishlist",
            name="wprice",
        ),
        migrations.AddField(
            model_name="wishlist",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="wishlist",
            name="user",
            field=models.ForeignKey(
                default=2, on_delete=django.db.models.deletion.CASCADE, to="myapp.user"
            ),
            preserve_default=False,
        ),
    ]
