# Generated by Django 5.0.6 on 2024-06-23 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0013_cart"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="payment",
            field=models.BooleanField(default=False),
        ),
    ]
