# Generated by Django 5.0.6 on 2024-06-24 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0015_cart_cprice_cart_cqty_cart_tprice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="cprice",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
