# Generated by Django 5.0.4 on 2024-06-24 18:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0017_alter_cart_cprice_alter_cart_tprice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="tprice",
            field=models.PositiveIntegerField(),
        ),
    ]
