# Generated by Django 5.0.4 on 2024-06-24 18:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0018_alter_cart_tprice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="cprice",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
