# Generated by Django 5.0.4 on 2024-06-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0020_rename_cprice_cart_ccprice"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="ccprice",
        ),
        migrations.AddField(
            model_name="cart",
            name="cprice",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
