# Generated by Django 5.0.4 on 2024-06-25 09:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0021_remove_cart_ccprice_cart_cprice"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="cprice",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="cqty",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="tprice",
        ),
    ]
